/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qfkswmskollpngnmsduc"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFma3N3bXNrb2xscG5nbm1zZHVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3Mzg1ODAsImV4cCI6MjA4MDMxNDU4MH0._qH-grGvkp7fqBDpcSNMTIHy4PYNwrc0hn6IVm0-OoA"